export const SITE_SEO = {
  siteName: 'Andejecruher',
  siteUrl: 'https://andejecruher.com',
  author: 'Andejecruher',
  jobTitle: 'Full Stack Developer (backend-first)',
  defaultTitle: 'Andejecruher · Full Stack Developer (backend-first)',
  defaultDescription:
    'Full Stack Developer (backend-first) specialized in Backend Engineering, Frontend Development, SaaS Architecture, REST APIs, AI Agents, Automation and enterprise integrations.',
  defaultSocialImage: '/og-image.jpg',
  defaultSocialImageAlt:
    'Andejecruher — Full Stack Developer (backend-first), Backend Engineering, SaaS, REST APIs, AI Agents and Automation',
  twitterSite: '@Andejecruher',
  twitterCreator: '@Andejecruher',
  ogImageWidth: 1200,
  ogImageHeight: 630,
  favicon: '/favicon.svg',
  themeColor: '#020b11',
  sameAs: [
    'https://github.com/Andejecruher',
    'https://www.linkedin.com/in/andejecruher/',
    'https://x.com/Andejecruher',
  ],
  knowsAbout: [
    'Laravel',
    'Node.js',
    'Express',
    'FastAPI',
    'Python',
    'React',
    'Next.js',
    'Vue.js',
    'Astro',
    'Docker',
    'GraphQL',
    'SaaS',
    'Backend Engineering',
    'Frontend Development',
    'REST APIs',
    'AI Agents',
    'Automation',
    'Enterprise Integrations',
    'DevOps',
    'CI/CD',
    'Infrastructure as Code',
  ],
  locales: {
    es: 'es_ES',
    en: 'en_US',
  } as const,
} as const;
